name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build new
        run: docker-compose down
      - name: Build the Docker imaged
        run: docker-compose build
      - name: Test
        run: docker-compose up -d
